package edu.cnm.deepdive.service;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import edu.cnm.deepdive.model.Game;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.logging.HttpLoggingInterceptor;
import okhttp3.logging.HttpLoggingInterceptor.Level;
import retrofit2.Call;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;
import retrofit2.http.Body;
import retrofit2.http.GET;
import retrofit2.http.POST;
import retrofit2.http.Path;

public interface CodebreakerServiceProxy {

  /**
   * Sends a request to the web service to generate a new secret code (start a new game).
   *
   * @param game "stub of {@link Game} specifying the characters that can be used in the code
   *             generated by the web service, and the length of the code to be generated.
   * @return {@link Call} instance that may be used to send the HTTP request and receive the response.
   */

  @POST("codes")
  Call<Game> startGame(@Body Game game);

  @GET("codes/{id}")
  Call<Game> getGame(@Path("id") String id);

  static CodebreakerServiceProxy getInstance() {

    return InstanceHolder.INSTANCE;

  }

  class InstanceHolder {


    private static final CodebreakerServiceProxy INSTANCE;

    static {

      Gson gson = new GsonBuilder()
          .excludeFieldsWithoutExposeAnnotation()
          .setDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ")
          .create();

      HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();

      interceptor.setLevel(Level.BODY);

      OkHttpClient client = new OkHttpClient.Builder()
          .addInterceptor(interceptor)
          .build();

      Retrofit retrofit = new Retrofit.Builder()
          .baseUrl("https://ddc-java.services/codebreaker/")
          .addConverterFactory(GsonConverterFactory.create(gson))
          .client(client)
          .build();

      INSTANCE = retrofit.create(CodebreakerServiceProxy.class);

    }

  }
}
